"""purchase and sales orders

Revision ID: 2b1bc2d1c4c0
Revises: b7e1c0d2f3a4
Create Date: 2026-07-03 20:55:37.896978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1bc2d1c4c0'
down_revision: Union[str, None] = 'b7e1c0d2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_no', sa.String(length=30), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('order_date', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_no'), ['po_no'], unique=True)

    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_no', sa.String(length=30), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('order_date', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_so_no'), ['so_no'], unique=True)

    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_po_id'), ['po_id'], unique=False)

    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_lines_so_id'), ['so_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_so_id'))

    op.drop_table('sales_order_lines')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_po_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_so_no'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_no'))

    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
